### ISSUE TITLE
CSS Errors

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-ashish/TechSquad#3]
Sorry! We found the following errors (9)
URI : TextArea
11	#header	Value Error : color lightgrey is not a color value : lightgrey lightgrey
18	h1	Value Error : font-size only 0 can be a length. You must put a unit after your number : 18 18
19	h1	Value Error : font-style bold is not a font-style value : bold bold
20	h1	Value Error : margin-left only 0 can be a length. You must put a unit after your number : 20 20
23	h1 a	Value Error : color lightgrey is not a color value : lightgrey lightgrey
27	h1 a	Value Error : font-size only 0 can be a length. You must put a unit after your number : 14 14
32	#herounit	Value Error : background-color grey is not a color value : grey grey
49	h2	Value Error : font-size only 0 can be a length. You must put a unit after your number : 18 18
50	h2	Value Error : font-style bold is not a font-style value : bold bold

**Comment by ibigrock-ashish** [comment]
Done
